
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA LBRACE LBRACKET NUMBER RBRACE RBRACKET STRINGjson : LBRACKET elements RBRACKETelements : object COMMA elementselements : objectobject : LBRACE members RBRACEmembers : pair COMMA membersmembers : pairpair : STRING COLON valuevalue : STRINGvalue : NUMBERvalue : object'
    
_lr_action_items = {'LBRACKET':([0,],[2,]),'$end':([1,6,],[0,-1,]),'LBRACE':([2,7,14,],[5,5,5,]),'RBRACKET':([3,4,11,12,],[6,-3,-2,-4,]),'COMMA':([4,9,12,16,17,18,19,],[7,13,-4,-8,-7,-9,-10,]),'STRING':([5,13,14,],[10,10,16,]),'RBRACE':([8,9,12,15,16,17,18,19,],[12,-6,-4,-5,-8,-7,-9,-10,]),'COLON':([10,],[14,]),'NUMBER':([14,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'json':([0,],[1,]),'elements':([2,7,],[3,11,]),'object':([2,7,14,],[4,4,19,]),'members':([5,13,],[8,15,]),'pair':([5,13,],[9,9,]),'value':([14,],[17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> json","S'",1,None,None,None),
  ('json -> LBRACKET elements RBRACKET','json',3,'p_json','parser_json.py',6),
  ('elements -> object COMMA elements','elements',3,'p_elements_multiple','parser_json.py',10),
  ('elements -> object','elements',1,'p_elements_single','parser_json.py',14),
  ('object -> LBRACE members RBRACE','object',3,'p_object','parser_json.py',18),
  ('members -> pair COMMA members','members',3,'p_members_multiple','parser_json.py',22),
  ('members -> pair','members',1,'p_members_single','parser_json.py',27),
  ('pair -> STRING COLON value','pair',3,'p_pair','parser_json.py',31),
  ('value -> STRING','value',1,'p_value_string','parser_json.py',37),
  ('value -> NUMBER','value',1,'p_value_number','parser_json.py',42),
  ('value -> object','value',1,'p_value_object','parser_json.py',46),
]
